### ISSUE TITLE
Blank out text in the tab

### ISSUE THREAD

**Issue by TheJaredWilcurt** [dandydanny/darknewtab#5]
Here is an example of a different extension that does this (but isn't dark):

* https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij

**Comment by IEGPizza** [comment]
That is the one thing keeping me from using this extension.
@dandydanny you stated "4. I wanted to minimize distractions" so why leave the title and even add an extra word to it?

**Comment by dandydanny** [comment]
My rationale for prepending the word "Dark" in front of the existing "New Tab" string, was to make it clear to the user that a 3rd party extension is now controlling the appearance of newly opened tabs. 

With that said, I've noticed Chrome now diligently notify the user upon first run of new-tab-appearance-changing extensions, making the above provision redundant. 

I've grown tired of reading that string as well. I'll merge the changes and push the update to Chrome Web Store. 

Thank you @TheJaredWilcurt and @IEGPizza for your input and your support.

**Comment by IEGPizza** [comment]
Thanks! Much appreciated
